lz4kd: Add more needed headers
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:21:26: error: call to
undeclared function 'crypto_tfm_ctx'; ISO C99 and later do not support implicit
function declarations [-Wimplicit-function-declaration] 21 | struct lz4kd_ctx
*ctx = crypto_tfm_ctx(tfm); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:21:20: error:
incompatible integer to pointer conversion initializing 'struct lz4kd_ctx *'
with an expression of type 'int' [-Wint-conversion] 21 | struct lz4kd_ctx *ctx =
crypto_tfm_ctx(tfm); | ^ ~~~~~~~~~~~~~~~~~~~
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:32:26: error: call to
undeclared function 'crypto_tfm_ctx'; ISO C99 and later do not support implicit
function declarations [-Wimplicit-function-declaration] 32 | struct lz4kd_ctx
*ctx = crypto_tfm_ctx(tfm); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:32:20: error:
incompatible integer to pointer conversion initializing 'struct lz4kd_ctx *'
with an expression of type 'int' [-Wint-conversion] 32 | struct lz4kd_ctx *ctx =
crypto_tfm_ctx(tfm); | ^ ~~~~~~~~~~~~~~~~~~~
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:39:26: error: call to
undeclared function 'crypto_tfm_ctx'; ISO C99 and later do not support implicit
function declarations [-Wimplicit-function-declaration] 39 | struct lz4kd_ctx
*ctx = crypto_tfm_ctx(tfm); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:39:20: error:
incompatible integer to pointer conversion initializing 'struct lz4kd_ctx *'
with an expression of type 'int' [-Wint-conversion] 39 | struct lz4kd_ctx *ctx =
crypto_tfm_ctx(tfm); | ^ ~~~~~~~~~~~~~~~~~~~
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:82:9: error: call to
undeclared function 'crypto_register_alg'; ISO C99 and later do not support
implicit function declarations [-Wimplicit-function-declaration] 82 | return
crypto_register_alg(&alg_lz4kd); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:87:2: error: call to
undeclared function 'crypto_unregister_alg'; ISO C99 and later do not support
implicit function declarations [-Wimplicit-function-declaration] 87 |
crypto_unregister_alg(&alg_lz4kd); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:95:21: error: expected
parameter declarator 95 | MODULE_ALIAS_CRYPTO("lz4kd"); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:95:21: error: expected
')' /home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:95:20: note: to
match this '(' 95 | MODULE_ALIAS_CRYPTO("lz4kd"); | ^
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:95:1: error: type
specifier missing, defaults to 'int'; ISO C99 and later do not support implicit
int [-Wimplicit-int] 95 | MODULE_ALIAS_CRYPTO("lz4kd"); | ^ | int
/home/zenin/aicp-16/kernel/xiaomi/sm8735/crypto/lz4kd.c:95:20: error: a function
declaration without a prototype is deprecated in all versions of C
[-Werror,-Wstrict-prototypes] 95 | MODULE_ALIAS_CRYPTO("lz4kd"); | ^
| void 12 errors generated.

Change-Id: I2f350a7109cd4f9ba1d92e840fab5f2f
Signed-off-by: zenin1504 <me.zenin1504.dev@gmail.com>